name: 'Debugging with tmate'
description: 'Debug your GitHub Actions Environment interactively by using SSH or a Web shell'
author: 'Max Schmitt'
runs:
  using: 'node12'
  main: 'lib/index.js'
inputs:
  sudo:
    description: 'If apt should be executed with sudo or without'
    required: false
    default: 'true'
  limit-access-to-actor:
    description: 'If only the public SSH keys of the user triggering the workflow should be authorized'
    required: false
    default: 'false'
  install-linux-dependencies:
    description: 'this step install installation of any dependencies for tmate using the package manager'
    required: false
    default: 'true'